import AppKit
import Foundation
import KilnCore

/// Thin `@MainActor` orchestrator wiring the share sheet's include-options
/// onto KilnCore's `ShareExporter`. Runs the save panel, synthesizes a
/// Modelfile (the real fuse→Modelfile pipeline lands post-M8 — see
/// `SPEC.md §9`), builds the `ShareManifest`, calls `KilnShare.export`, and
/// projects the result into the UI-layer `ShareBundleSummary` type.
///
/// Kept as a namespaced enum (no instance state) so it's trivially testable
/// and doesn't need threading through `AppModel`. If a richer surface shows
/// up later — e.g. progress ticks from the exporter — promote this to an
/// `@Observable ShareModel` without changing the call site.
enum ShareController {
    /// Top-level entry point the share sheet's `onExport` closure calls.
    ///
    /// Returns `nil` for the two non-error paths the sheet treats identically:
    ///   - the user cancelled the save panel,
    ///   - the project has no trained adapter yet (should be impossible in
    ///     the Complete stage, but we guard rather than crash).
    /// Returns `nil` on export failure too, for M8 — M9 will surface the
    /// typed `ShareExporterError` via a toast. For now the sheet stays in its
    /// "ready to retry" state rather than silently claiming success.
    @MainActor
    static func runExport(
        project: Project,
        options: ShareIncludeOptions
    ) async -> ShareBundleSummary? {
        guard let adapterURL = project.trainingReport?.adapterURL else {
            return nil
        }

        let defaultName = "\(project.slug).kiln"
        guard let destinationURL = presentSavePanel(defaultName: defaultName) else {
            return nil
        }

        // Synthesize a Modelfile in a scratch temp file. The real fuse+convert
        // pipeline that emits one lives in M9+; until then this inline string
        // is the only thing a recipient's `ollama create` needs to run.
        let modelfileURL: URL
        do {
            modelfileURL = try writeSynthesizedModelfile(for: project)
        } catch {
            return nil
        }
        defer { try? FileManager.default.removeItem(at: modelfileURL) }

        let manifest = ShareManifest(
            voiceName: project.slug,
            adapterURL: adapterURL,
            modelfileURL: modelfileURL,
            readmeText: options.readme ? defaultReadme(for: project) : nil,
            signatureCardPNG: options.signatureCard ? signaturePNG(for: project) : nil,
            sourceManifestText: options.sourceManifest ? sourceManifestText(for: project) : nil
        )

        do {
            let bundle = try await KilnShare.export(manifest: manifest, to: destinationURL)
            return ShareBundleSummary(
                filename: destinationURL.lastPathComponent,
                bundleURL: bundle.bundleURL,
                sizeBytes: bundle.sizeBytes,
                sha256Prefix: String(bundle.sha256.prefix(12))
            )
        } catch {
            // Swallow for M8 — a typed error surface (toast + retry affordance)
            // is on the M9 polish list.
            return nil
        }
    }

    // MARK: - Save panel

    @MainActor
    private static func presentSavePanel(defaultName: String) -> URL? {
        let panel = NSSavePanel()
        panel.title = "Export Kiln voice"
        panel.prompt = "Export"
        panel.nameFieldStringValue = defaultName
        if let downloads = FileManager.default.urls(
            for: .downloadsDirectory, in: .userDomainMask
        ).first {
            panel.directoryURL = downloads
        }
        let response = panel.runModal()
        guard response == .OK, let url = panel.url else { return nil }
        return url
    }

    // MARK: - Manifest payloads

    private static func writeSynthesizedModelfile(for project: Project) throws -> URL {
        let baseTag = "mlx-community/Qwen2.5-\(project.modelSize.displayName)-Instruct-4bit"
        let voiceLabel = project.name.isEmpty ? "this voice" : project.name
        let text = """
        # Auto-generated by Kiln \(project.slug)
        FROM \(baseTag)
        PARAMETER temperature 0.8
        SYSTEM \"\"\"
        You speak in the voice of \(voiceLabel). Mirror the author's tone,
        rhythm, and vocabulary. Stay grounded — never invent biographical
        claims the author hasn't made.
        \"\"\"
        """
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("kiln-modelfile-\(UUID().uuidString)")
        try text.write(to: url, atomically: true, encoding: .utf8)
        return url
    }

    private static func defaultReadme(for project: Project) -> String {
        let slug = project.slug
        let displayName = project.name.isEmpty ? slug : project.name
        return """
        # \(displayName) — Kiln voice

        This bundle contains the fused LoRA adapter and the Ollama Modelfile
        needed to run the voice locally. It was trained entirely on the
        author's machine; no text was uploaded to produce it.

        ## Import

            ollama create kiln-\(slug) -f Modelfile
            ollama run kiln-\(slug)

        ## Files

        - `adapter.safetensors` — fused LoRA adapter weights.
        - `Modelfile` — Ollama recipe that loads the base model plus adapter.
        - `manifest.json` — SHA-256 of every file, plus the voice name.
        """
    }

    private static func signaturePNG(for _: Project) -> Data? {
        // StyleSignature rendering threads into Project in a later milestone;
        // until then we omit the signature rather than ship a placeholder.
        return nil
    }

    private static func sourceManifestText(for project: Project) -> String? {
        guard let report = project.ingestReport else { return nil }
        let folder = project.folderName ?? "(unknown folder)"
        return """
        # Kiln source manifest

        Project:      \(project.name)
        Source folder: \(folder)

        Files discovered: \(report.filesDiscovered)
        Files parsed:     \(report.filesParsed)
        Chunks kept:      \(report.chunksAfterQuality) of \(report.chunksBeforeDedup)

        No original text is included in this bundle. The counts above
        describe the corpus that was used to train the adapter shipped
        alongside.
        """
    }
}
